apiVersion: v1
kind: Service
metadata:
  name: go-web-hello-world
  labels:
    run: go-web-hello-world
spec:
  type: NodePort
  ports:
    - port: 31080
      protocol: TCP
      targetPort: 8081
  selector:
    app: go-web-hello-world
