apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-hello-world
  template:
    metadata:
      labels:
        app: go-web-hello-world
    spec:
      containers:
      - image: yanggongbi/go-web-hello-world:v0.1
        name: go-web-hello-world
        ports:
          - containerPort: 8081
